pipeline:
    build:
        image: maven:3.3.9-jdk-8
        environment:
           - CATALINA_HOME=/opt/apache-tomcat-8/apache-tomcat-8.5.6
           - JAVA_HOME=/usr/lib/jvm/default-java
           - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/games:/snap/bin
        commands:
          #We have to cd into each subdirectory: jpabase entities overlay webapp
           - java -version
           - mvn -version
           - cd gt-fhir-entities
           - mvn clean install
           - cd ../gt-fhir-jpabase
           - mvn clean install
           - cd ../gt-fhir-overlay
           - mvn clean install
           - cd ../gt-fhir-webapp
           - mvn clean install
           - GT-FHIRPostInstallTest.sh localhost 8080
services:
    # authentication:
    #    image: openid-mitr
    db:
         image: postgres
         environment:
          - POSTGRES_USER=omop_v5
          - POSTGRES_PASSWORD=i3lworks
          - POSTGRES_DATABASE=postgres
